version: '3'

services:
  ffmpeg-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /tmp/ffmpeg_api:/tmp/ffmpeg_api
    environment:
      - WORKERS=4
      - THREADS=2
      - TIMEOUT=600         # 10 minutes HTTP timeout
      - FFMPEG_TIMEOUT=0    # FFmpeg timeout (0 = no timeout)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s