services:
  ffmpeg-api:
    build: .
    deploy:
      resources:
        limits:
          cpus: '2'
    volumes:
      - ffmpeg_api:/tmp/ffmpeg_api
    environment:
      - WORKERS=2
      - THREADS=2
      - TIMEOUT=600         # 10 minutes HTTP timeout
      - FFMPEG_TIMEOUT=0    # FFmpeg timeout (0 = no timeout)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.core.somaxconn: 1024
    labels:
      - 'traefik.http.middlewares.ffmpeg-api.basicauth.users=test:$2b$12$JjB6HeBSszfIUjW1WQX5ruJQek5tisC5V5SLKi7N4UjoZqZ0wkMf2'

volumes:
  ffmpeg_api: